name: Update Postcodes

on:
  schedule:
    - cron: "0 0 1 * *" # 毎月1日に実行 (UTC基準)
  workflow_dispatch:      # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: npm run update

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/postcodes.json
          git commit -m "chore: update postcodes.json [skip ci]" || echo "No changes"
          git push
